### ISSUE TITLE
Video embedding enhancement: (Click this ticket for details)

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#55]
Embed Video Customization Requirements:

The embed model should provide users with the following capabilities when embedding a video:

1. **Custom Branding Options:**

a. Users can upload an SVG asset, such as the company logo or relevant branding element.
b. Ability to add a watermark to the video.
c. Customize the frame color to align with the brand guidelines of the enterprise. 

2. **Preview Functionality:**

a. Users should have the ability to preview the video with applied customizations before finalizing the embedding process.

**Comment by pragatiib** [comment]
this is done. - commented for myself.
