### ISSUE TITLE
Feedback from tech team on Veel App web

### ISSUE THREAD

**Issue by Sahas664** [AppBoxTech/veel-design#77]
- [x] Talk to priyanka about the contents of the login and signup error message. P0
- [x] Password field for Sign-up is missing. p0
- [x] Video upload state? 
- [x] Upload progress of video?
- [x]  How should search screen appear before and after search.  
- [x] How to go back from Video screen, and scroll to other videos from Feed details. 
- [ ] How to scale feed section in multiple screen resolutions

**Comment by pragatiib** [comment]
How to scale feed section in multiple screen resolutions
 - design team has decided to do this later, as it has to be done on throughout the system.
